import uiScriptLocale

AETHERFALL_SELECT_PATH = "d:/ymir work/ui/aetherfall/select/"
AETHERFALL_CHARACTER_PATH = "d:/ymir work/ui/aetherfall/character/"

window = {
    "name": "SelectCharacterWindow",
    "x": 0,
    "y": 0,
    "width": SCREEN_WIDTH,
    "height": SCREEN_HEIGHT,
    "children": (
        {
            "name": "BackGround",
            "type": "expanded_image",
            "x": 0,
            "y": 0,
            "image": AETHERFALL_SELECT_PATH + "select_valoria.sub",
            "x_scale": float(SCREEN_WIDTH) / 1024.0,
            "y_scale": float(SCREEN_HEIGHT) / 768.0,
        },
        {"name": "EmpireArea_A", "type": "image", "x": 120, "y": 176, "image": AETHERFALL_CHARACTER_PATH + "faction_mora_card.sub"},
        {"name": "EmpireArea_B", "type": "image", "x": 300, "y": 176, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_purple_card.sub"},
        {"name": "EmpireArea_C", "type": "image", "x": 480, "y": 176, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_blue_card.sub"},
        {"name": "EmpireAreaFlag_A", "type": "image", "x": 120, "y": 176, "image": AETHERFALL_CHARACTER_PATH + "faction_mora_card.sub"},
        {"name": "EmpireAreaFlag_B", "type": "image", "x": 300, "y": 176, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_purple_card.sub"},
        {"name": "EmpireAreaFlag_C", "type": "image", "x": 480, "y": 176, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_blue_card.sub"},
        {
            "name": "empire_board",
            "type": "window",
            "x": 46,
            "y": 420,
            "width": 320,
            "height": 248,
            "children": (
                {"name": "flag_board", "type": "bar", "x": 0, "y": 0, "width": 320, "height": 248, "color": 0xaa090b10},
                {"name": "text_board", "type": "window", "x": 18, "y": 18, "width": 284, "height": 140},
                {"name": "EmpireFlag_A", "type": "image", "x": 96, "y": 20, "image": AETHERFALL_CHARACTER_PATH + "faction_mora_card.sub"},
                {"name": "EmpireFlag_B", "type": "image", "x": 96, "y": 20, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_purple_card.sub"},
                {"name": "EmpireFlag_C", "type": "image", "x": 96, "y": 20, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_blue_card.sub"},
                {
                    "name": "prev_text_button",
                    "type": "button",
                    "x": 18,
                    "y": 176,
                    "default_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
                    "over_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
                    "down_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
                    "text": "<",
                },
                {
                    "name": "next_text_button",
                    "type": "button",
                    "x": 110,
                    "y": 181,
                    "default_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
                    "over_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
                    "down_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
                    "text": ">",
                },
            ),
        },
        {
            "name": "left_button",
            "type": "button",
            "x": 46,
            "y": SCREEN_HEIGHT - 124,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "text": "<",
        },
        {
            "name": "right_button",
            "type": "button",
            "x": 238,
            "y": SCREEN_HEIGHT - 119,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "text": ">",
        },
        {
            "name": "select_button",
            "type": "button",
            "x": SCREEN_WIDTH - 430,
            "y": SCREEN_HEIGHT - 122,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "text": uiScriptLocale.EMPIRE_SELECT,
        },
        {
            "name": "exit_button",
            "type": "button",
            "x": 34,
            "y": SCREEN_HEIGHT - 126,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "text": uiScriptLocale.EMPIRE_EXIT,
        },
    ),
}
