import uiScriptLocale

AETHERFALL_SELECT_PATH = "d:/ymir work/ui/aetherfall/select/"
AETHERFALL_CHARACTER_PATH = "d:/ymir work/ui/aetherfall/character/"

PANEL_X = 38
PANEL_Y = 94
PANEL_W = 310
PANEL_H = 560

window = {
    "name": "SelectCharacterWindow",
    "x": 0,
    "y": 0,
    "width": SCREEN_WIDTH,
    "height": SCREEN_HEIGHT,
    "children": (
        {
            "name": "BackGround",
            "type": "expanded_image",
            "x": 0,
            "y": 0,
            "image": AETHERFALL_SELECT_PATH + "select_myr.sub",
            "x_scale": float(SCREEN_WIDTH) / 1024.0,
            "y_scale": float(SCREEN_HEIGHT) / 768.0,
        },
        {"name": "name_warrior", "type": "image", "x": PANEL_X + 18, "y": PANEL_Y + 84, "image": AETHERFALL_CHARACTER_PATH + "class_klingenwaechter.sub"},
        {"name": "name_assassin", "type": "image", "x": PANEL_X + 18, "y": PANEL_Y + 150, "image": AETHERFALL_CHARACTER_PATH + "class_schattenlaeufer.sub"},
        {"name": "name_sura", "type": "image", "x": PANEL_X + 18, "y": PANEL_Y + 216, "image": AETHERFALL_CHARACTER_PATH + "class_runenmagier.sub"},
        {"name": "name_shaman", "type": "image", "x": PANEL_X + 18, "y": PANEL_Y + 282, "image": AETHERFALL_CHARACTER_PATH + "class_seelenrufer.sub"},
        {"name": "name_eisenjaeger", "type": "image", "x": PANEL_X + 18, "y": PANEL_Y + 348, "image": AETHERFALL_CHARACTER_PATH + "class_eisenjaeger.sub"},
        {"name": "name_aetherbrut", "type": "image", "x": PANEL_X + 18, "y": PANEL_Y + 414, "image": AETHERFALL_CHARACTER_PATH + "class_aetherbrut.sub"},
        {
            "name": "character_board",
            "type": "window",
            "x": PANEL_X,
            "y": PANEL_Y,
            "width": PANEL_W,
            "height": PANEL_H,
            "children": (
                {"name": "BoardShade", "type": "bar", "x": 0, "y": 0, "width": PANEL_W, "height": PANEL_H, "color": 0xaa090b10},
                {"name": "BoardInner", "type": "bar", "x": 1, "y": 1, "width": PANEL_W - 2, "height": PANEL_H - 2, "color": 0x441a120d},
                {"name": "EmpireFlag_A", "type": "image", "x": 18, "y": 18, "image": AETHERFALL_CHARACTER_PATH + "faction_mora_card.sub"},
                {"name": "EmpireFlag_B", "type": "image", "x": 18, "y": 18, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_purple_card.sub"},
                {"name": "EmpireFlag_C", "type": "image", "x": 18, "y": 18, "image": AETHERFALL_CHARACTER_PATH + "faction_myr_blue_card.sub"},
                {
                    "name": "EmpireName",
                    "type": "text",
                    "x": 158,
                    "y": 28,
                    "width": 126,
                    "height": 18,
                    "text_horizontal_align": "center",
                    "text": uiScriptLocale.SELECT_EMPIRE_NAME,
                },
                {
                    "name": "GuildName",
                    "type": "text",
                    "x": 158,
                    "y": 54,
                    "width": 126,
                    "height": 18,
                    "text_horizontal_align": "center",
                    "text": uiScriptLocale.SELECT_NO_GUILD,
                },
                {"name": "gauge_hth", "type": "gauge", "x": 150, "y": 372, "width": 106, "color": "red"},
                {"name": "gauge_int", "type": "gauge", "x": 150, "y": 402, "width": 106, "color": "yellow"},
                {"name": "gauge_str", "type": "gauge", "x": 150, "y": 432, "width": 106, "color": "purple"},
                {"name": "gauge_dex", "type": "gauge", "x": 150, "y": 462, "width": 106, "color": "blue"},
                {"name": "character_name_label", "type": "text", "x": 18, "y": 356, "text": uiScriptLocale.SELECT_NAME},
                {"name": "character_name_value", "type": "text", "x": 150, "y": 356, "text": ""},
                {"name": "character_level", "type": "text", "x": 18, "y": 386, "text": uiScriptLocale.SELECT_LEVEL},
                {"name": "character_level_value", "type": "text", "x": 150, "y": 386, "text": ""},
                {"name": "character_play_time", "type": "text", "x": 18, "y": 416, "text": uiScriptLocale.SELECT_PLAYTIME},
                {"name": "character_play_time_value", "type": "text", "x": 150, "y": 416, "text": ""},
                {"name": "character_hth", "type": "text", "x": 18, "y": 446, "text": uiScriptLocale.SELECT_HP},
                {"name": "character_hth_value", "type": "text", "x": 266, "y": 446, "text": ""},
                {"name": "character_int", "type": "text", "x": 18, "y": 476, "text": uiScriptLocale.SELECT_SP},
                {"name": "character_int_value", "type": "text", "x": 266, "y": 476, "text": ""},
                {"name": "character_str", "type": "text", "x": 18, "y": 506, "text": uiScriptLocale.SELECT_ATT_GRADE},
                {"name": "character_str_value", "type": "text", "x": 266, "y": 506, "text": ""},
                {"name": "character_dex", "type": "text", "x": 18, "y": 536, "text": uiScriptLocale.SELECT_DEX_GRADE},
                {"name": "character_dex_value", "type": "text", "x": 266, "y": 536, "text": ""},
            ),
        },
        {
            "name": "start_button",
            "type": "button",
            "x": SCREEN_WIDTH - 444,
            "y": SCREEN_HEIGHT - 118,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "text": uiScriptLocale.SELECT_SELECT,
        },
        {
            "name": "create_button",
            "type": "button",
            "x": SCREEN_WIDTH - 444,
            "y": SCREEN_HEIGHT - 118,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_abenteuer_beginnen.sub",
            "text": uiScriptLocale.SELECT_CREATE,
        },
        {
            "name": "delete_button",
            "type": "button",
            "x": SCREEN_WIDTH - 444,
            "y": SCREEN_HEIGHT - 178,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "text": uiScriptLocale.SELECT_DELETE,
        },
        {
            "name": "exit_button",
            "type": "button",
            "x": 34,
            "y": SCREEN_HEIGHT - 126,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "text": uiScriptLocale.SELECT_EXIT,
        },
        {
            "name": "left_button",
            "type": "button",
            "x": int(SCREEN_WIDTH / 2) - 164,
            "y": SCREEN_HEIGHT - 126,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_zurueck.sub",
            "text": "<",
        },
        {
            "name": "right_button",
            "type": "button",
            "x": int(SCREEN_WIDTH / 2) + 26,
            "y": SCREEN_HEIGHT - 121,
            "default_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "over_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "down_image": AETHERFALL_CHARACTER_PATH + "btn_name_pruefen.sub",
            "text": ">",
        },
    ),
}
